# Generated by Django 3.2.12 on 2023-12-02 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subordinates',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='подчиненные'),
        ),
    ]
