# Generated by Django 3.2.12 on 2023-12-02 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subordinates',
            field=models.ManyToManyField(blank=True, help_text='Выберите подчиненных данного пользователя', related_name='bosses', related_query_name='bosses', to=settings.AUTH_USER_MODEL, verbose_name='подчиненные'),
        ),
    ]
