# Generated by Django 3.2.12 on 2023-11-25 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tasks', '0001_initial'), ('tasks', '0002_task_user'), ('tasks', '0003_rename_user_task_users'), ('tasks', '0004_auto_20231125_2330'), ('tasks', '0005_alter_task_name')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('users', models.ManyToManyField(help_text='Выберите исполнителей задачи', to=settings.AUTH_USER_MODEL, verbose_name='исполняющий')),
                ('deadline', models.DateField(blank=True, help_text='Укажите срок сдачи задачи', null=True, verbose_name='дедлайн')),
                ('name', models.CharField(help_text='Укажите название задачи', max_length=100, verbose_name='название')),
                ('status', models.BooleanField(default=False, help_text='Статус выполнения задачи', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['-deadline', '-status', '-date_created'],
            },
        ),
    ]
