# Generated by Django 3.2.12 on 2023-11-27 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20231127_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_end',
            field=models.DateField(help_text='Укажите срок окончания работы над задачи', verbose_name='конец работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_start',
            field=models.DateField(help_text='Укажите срок начала работы над задачи', verbose_name='начало работы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='random_users_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Выберите количество исполнителей задачи, которые добавятся к, уже выбранным вами исполнителям, из числа менее загруженных сотрудников', validators=[django.core.validators.MinValueValidator(0)], verbose_name='количество случайных исполнителей'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(help_text='Выберите исполнителей задачи', null=True, related_name='tasks', related_query_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнители'),
        ),
    ]
