# Generated by Django 3.2.12 on 2023-11-27 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20231127_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Выберите исполнителей задачи', null=True, related_name='tasks', related_query_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнители'),
        ),
    ]
