# Generated by Django 3.2.12 on 2023-11-27 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Выберите исполнителей задачи', related_name='tasks', related_query_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнители'),
        ),
    ]
