# Generated by Django 3.2.12 on 2023-12-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_completed',
            new_name='time_completed',
        ),
    ]
