# Generated by Django 3.2.12 on 2023-12-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_date_completed_task_time_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, help_text='Время за которое была сдана работа', null=True, verbose_name='время сдачи'),
        ),
    ]
