# Generated by Django 3.2.16 on 2024-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20231204_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Укажите название задачи', max_length=10000, verbose_name='название'),
        ),
    ]
